spring:
    profiles:
        active: local
    
    application:
        name: myapp

server:
    port: 8080

springdoc:
    swagger-ui:
        path: /swagger/swagger-ui # http://localhost:8080/swagger/swagger-ui
    api-docs:
        path: /swagger/swagger-docs # http://localhost:8080/swagger/swagger-docs
