spring:
    profiles:
        active: local
    
    application:
        name: myapp

server:
    port: 8080

springdoc:
    swagger-ui:
        path: /swagger/swagger-ui # http://localhost:8080/swagger/swagger-ui
    api-docs:
        path: /swagger/swagger-docs # http://localhost:8080/swagger/swagger-docs

# Actuator 설정
management:
    endpoints:
        web:
            exposure:
                include: health, metrics, loggers, info, threaddump, env # 노출할 Actuator 엔드포인트 지정
    endpoint:
        health:
            show-details: always  # health 상태에 대한 상세 정보 노출
        metrics:
            enabled: true  # 메트릭 활성화
        loggers:
            enabled: true  # 로그 레벨 동적 변경 활성화
        env:
            enabled: true  # 환경 변수 조회 활성화
    info:
        env:
            enabled: true  # 애플리케이션 정보 노출 활성화