apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk029-stock-market
  labels:
    app: sk029-stock-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk029-stock-market
  template:
    metadata:
      labels:
        app: sk029-stock-market
    spec:
      containers:
        - name: sk029-stock-market
          image: amdp-registry.skala-ai.com/skala25a/sk029-stock-market:1.0.0
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred