apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk029-stock-market
  labels:
    app: sk029-stock-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk029-stock-market
  template:
    metadata:
      labels:
        app: sk029-stock-market
    spec:
      tolerations:
        - key: "control-plane"
          operator: "Equal"
          value: "amdp"
          effect: "NoSchedule"
      containers:
        - name: sk029-stock-market
        image: amdp-registry.skala-ai.com/skala25a/sk029-my-app:1.0.kaniko-docker-9-26bdb5c13c67
          ports:
            - containerPort: 8085
      imagePullSecrets:
        - name: regcred