apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk029-stock-market
  labels:
    app: sk029-stock-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk029-stock-market
  template:
    metadata:
      labels:
        app: sk029-stock-market
    spec:
      tolerations:
        - key: "control-plane"
          operator: "Equal"
          value: "amdp"
          effect: "NoSchedule"
      containers:
        - name: sk029-stock-market
          image: amdp-registry.skala-ai.com/skala25a/sk029-stock-market:1.0.0@sha256:b17d26f7148537f17b67f0729cfe3b36cb32a112704fa240ca71c4a44502761e
          ports:
            - containerPort: 8085
      imagePullSecrets:
        - name: regcred