apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-market
  labels:
    app: stock-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-market
  template:
    metadata:
      labels:
        app: stock-market
    spec:
      containers:
        - name: stock-market
          image: amdp-registry.skala-ai.com/skala25a/stock-market:1.0.0
          ports:
            - containerPort: 8080
