apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sk029-stock-market-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public-nginx
  rules:
    - host: sk029.stock-market.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sk029-stock-market
                port:
                  number: 8085
    - host: a55bf7a790b8e4b26b67a129d3263385-1094816387.ap-northeast-2.elb.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sk029-stock-market
                port:
                  number: 8085
